parameters:
  types: &types [
    "Bird",
    "Brute",
    "Fanged",
    "Flying",
    "Piscine",
    "Elder"
  ]
backend:
  name: git-gateway
  branch: master
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "elements"
    label: "Elements"
    label_singular: "Element"
    folder: "content/elements"
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    extension: 'md'
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Icon", name: "icon", widget: "image", required: false}
      - {label: "Description", name: "description", widget: "markdown", required: false}

  - name: "monsters"
    label: "Monsters"
    label_singular: "Monster"
    folder: "content/monsters"
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    extension: 'md'
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Cover Image", name: "coverImage", widget: "image", required: false}
      - {label: "Location", name: "location", widget: "string", required: false}
      - label: "Type"
        name: "type"
        widget: "select"
        options: *types
      - label: "Resistant to (when covered in mud or hardened)"
        name: "resistantTo"
        default: false
        widget: "relation"
        collection: "elements"
        searchFields: ["name"]
        valueField: "name"
        displayFields: ["name"]
        multiple: true
        required: false
      - label: "Standard damage"
        name: "standardDamage"
        default: false
        widget: "relation"
        collection: "elements"
        searchFields: ["name"]
        valueField: "name"
        displayFields: ["name"]
        multiple: true
        required: false
      - label: "Bonus damage"
        default: false
        name: "bonusDamage"
        widget: "relation"
        collection: "elements"
        searchFields: ["name"]
        valueField: "name"
        displayFields: ["name"]
        multiple: true
        required: false
      - label: "Immune to"
        default: false
        name: "immuneTo"
        widget: "relation"
        collection: "elements"
        searchFields: ["name"]
        valueField: "name"
        displayFields: ["name"]
        multiple: true
        required: false
      - label: "Tail severable?"
        name: "tailSeverable"
        widget: "boolean"
        default: false
        required: false
      - {label: "Description", name: "description", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
